// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evcdikzpnjjpotbkkshs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2Y2Rpa3pwbmpqcG90Ymtrc2hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2MTMwNjgsImV4cCI6MjA3NTE4OTA2OH0.xDiyfs8kUBHe5SGBkcSHX-U68IOb8ljG-jjYl02rBLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});