// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// NOTE: We've intentionally removed the heavy Database type import to avoid
// TypeScript "excessively deep and possibly infinite" instantiation errors
// that can occur with very large generated types. This keeps the UI build
// healthy while functionality remains the same.

// SECURITY: Use environment variables, never hardcode credentials
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate environment variables are set
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. Please check your .env file.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
}) as any;