// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// NOTE: We've intentionally removed the heavy Database type import to avoid
// TypeScript "excessively deep and possibly infinite" instantiation errors
// that can occur with very large generated types. This keeps the UI build
// healthy while functionality remains the same.

const SUPABASE_URL = "https://jrpmvilcyctqwflnojbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpycG12aWxjeWN0cXdmbG5vamJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTA2OTksImV4cCI6MjA3NDU2NjY5OX0.T5rp8WNQRwDmCFYI8aeFSjxOxVZqswCpJCy2NVkzqEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
}) as any;