// This file is automatically generated. Do not edit it directly.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          user_type: Database['public']['Enums']['user_type_enum']
          onboarding_completed: boolean
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id: string
          email: string
          user_type: Database['public']['Enums']['user_type_enum']
          onboarding_completed?: boolean
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          email?: string
          user_type?: Database['public']['Enums']['user_type_enum']
          onboarding_completed?: boolean
          created_at?: string | null
          updated_at?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      initialize_new_user: {
        Args: { p_user_id: string; p_email: string; p_user_type?: string }
        Returns: Json
      }
      complete_onboarding: {
        Args: { p_user_id: string; p_user_type: string }
        Returns: Json
      }
    }
    Enums: {
      user_type_enum: 'patient' | 'carer' | 'clinician' | 'researcher' | 'admin'
      gender_enum: 'male' | 'female' | 'non_binary' | 'other' | 'prefer_not_to_say'
      tracking_feature_enum: 'seizure' | 'tremor' | 'gait' | 'menstruation' | 'temperature' | 'mood' | 'energy' | 'sleep' | 'symptoms' | 'medication' | 'heart_rate' | 'blood_pressure' | 'weight' | 'exercise'
    }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T]